---
title: "Assignment Template"
format: html
---

```{r}
# Packages required
require(MASS)

# Load the Auto MPG dataset
auto <- read.csv(
  "https://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data",
  header = FALSE,
  sep = "",   # whitespace-separated file
  col.names = c("mpg", "cylinders", "displacement", "horsepower",
                "weight", "acceleration", "model_year", "origin", "car_name"),
  na.strings = "?"
)

auto <- na.omit(auto)

Y <- matrix(auto$mpg, ncol = 1)

Xpreds <- auto[, c("displacement", "horsepower", "weight", "acceleration")]

X <- as.matrix(cbind(1, scale(Xpreds)))

n <- nrow(X)

Xpreds
```

```{r}
#### Required Functions ####

library(ggplot2)
library(MASS)

#### Data Generating Functions ####

generate_lost <- function(grid_size, nsims){
  
  # Function to generate the prior distribution for the 
  # location of the lost fisherman
  # Args: 
  #       grid_size: the dimensions of the square search grid
  #       nsims: number of samples to base the prior distribution on
  
  mu_vec  <- c(grid_size/2, grid_size/2)
  sig_mat <- matrix(c(2, 1, 5, 5), 2,2)
  
  dat <- mvrnorm(nsims, mu_vec, sig_mat)
  dat <- round(abs(dat))
  
  prior <- matrix(rep(0,grid_size^2), grid_size, grid_size)
  for (i in 1:NROW(dat)){
    
    if (dat[i,1] < grid_size & dat[i,2] < grid_size){
      prior[dat[i,1], dat[i,2]] <- prior[dat[i,1], dat[i,2]] + 1
    }
    
  }
  prior <- prior/sum(prior)
  return(prior)
}

generate_fisherman <- function(grid_size){
  
  # Function to generate the true location of the lost fisherman.
  # This should not effect the search decision in any way!! It is unkown
  # to the search crew.
  # Args: 
  #       grid_size: the dimensions of the square search grid

  
  mu_vec  <- c(grid_size/2, grid_size/2)
  sig_mat <- matrix(c(2, 1, 5, 5), 2,2)
  
  location  <- round(mvrnorm(1, mu_vec, sig_mat))
  true_grid <- matrix(rep(0, grid_size^2), grid_size, grid_size)
  true_grid[location[1], location[2]] <- 1
  
  return(true_grid)
}

#### Simulation ####

search_size <- 20
unifs <- runif(search_size^2, min = 0.6, max = 0.9)
detect_pr <- matrix(unifs, ncol = search_size)

#...

```

### Gibbs Sampling

-   define max iterations

-   starting values for $\beta$ and $\sigma^2$ to initialize

-   store each pair that gets sampled

```{r}
#For the inverse gamma: rinvgamma()
install.packages("extraDistr")
library(extraDistr)
```

### Helper functions

```{r}
b_tilde = 0
M = diag(1,5)
mu_b = function(M, X, b_hat, b_tilde){
  solve((M + t(X)%*%X)) %*% (t(X)%*%X%*%b_hat + M%*%b_tilde)
}
A2 = function(y,b_tilde,mu_b){
  (t(y)%*%y) + (t(b_tilde)%*%M%*%b_tilde) - (t(mu_b)%*%(M+t(X)%*%X)%*%mu_b)
}

b_hat = function(X,Y){
  solve(t(X)%*%X)%*%t(X)%*%Y
}
```

### Conditional Posteriors

```{r}
beta_posterior = function(mu_b,sigma){
  var = sigma*solve((M+t(X)%*%X))
}

sigma_posterior = function(a,b,A2)
```
